[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sha2 = "0.10.9"
ed25519-dalek = "2.2.0"
rand = "0.9.2"
rocksdb = "0.20"
